name: OnPush
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 1) Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 2) Use Node 22
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - name: 3) "Create env file"
        run: |
          cp .env.example .env
      - name: 4) Install dependencies
        run: npm install --frozen-lockfile
        env:
          CI: true
      - name: 5) Build
        run: npm run build-ci
